import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { getAllProducts, getCategories } from '../api/fakeStoreApi'
import { ProductType } from '../types/apiResponses'
import styles from '../styles/Home.module.scss'
import ProductCard from '../components/ProductCard'

const Home: NextPage = ({categories, products}: InferGetServerSidePropsType<GetServerSideProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next Store
        </h1>
        <div>
          <ul>
            {categories.map((category: string, index: number) => <li key={index}>{category}</li>)}
          </ul>
          <div className={styles.card__container}>
            {products.map((product: ProductType) => <ProductCard key={product.id} product={product} />)}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const categories = await getCategories()
  const products = await getAllProducts()
  return {
    props: {
      categories,
      products,
    },
  } 
}

export default Home
